num1=int(input("enter the first number"))
num2=int(input("enter the second number"))
print(f"sum:{num1+num2}")
print(f"product:{num1*num2}")
print(f"quotient:{num1/num2}")
print(f"difference:{num1-num2}")
print(f"remainder:{num1%num2}")